replicaCount: 1

image:
  repository: <account-id>.dkr.ecr.ap-south-1.amazonaws.com/java-cicd-app
  tag: "1"

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: staging.PENDING.nip.io

nodeSelector:
  environment: staging
