apiVersion: v1
kind: Service
metadata:
  name: java-cicd-app-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: java-cicd-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
